import 'package:driver_application/localization/app_language.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  const AppLocalizations(this.languageCode);

  final String languageCode;

  static const supportedLocales = [Locale('en'), Locale('si'), Locale('ta')];

  static const Map<String, Map<String, String>> _translations = {
    'si': {
      'app_title': 'MediGo රියදුරු යෙදුම',
      'select_language': 'භාෂාව තෝරන්න',
      'english': 'English',
      'sinhala': 'සිංහල',
      'tamil': 'தமிழ்',
      'get_started': 'ආරම්භ කරන්න',
      'already_have_account': 'මට දැනටමත් ගිණුමක් ඇත',
      'start_tagline_title': 'වේගවත්, විශ්වාසදායක ගිලන් රථ කළමනාකරණය',
      'start_tagline_subtitle':
          'සජීවී ලුහුබැඳීම, සම්බන්ධීකරණය සහ කාර්යක්ෂම රෝගී සත්කාර සැපයීම',
      'feature_tracking': 'සජීවී රියදුරු සහ රෝගී ලුහුබැඳීම',
      'feature_dispatch': 'වේගවත් යොමු කිරීම සහ සම්බන්ධීකරණය',
      'feature_secure': 'ආරක්ෂිත රියදුරු ප්‍රවේශය',
      'login': 'පුරන්න',
      'signup': 'ලියාපදිංචි වන්න',
      'logout': 'ඉවත් වන්න',
      'cancel': 'අවලංගු කරන්න',
      'settings': 'සැකසුම්',
      'home': 'මුල් පිටුව',
      'history': 'ඉතිහාසය',
      'feedback_complaints': 'ප්‍රතිචාර / පැමිණිලි',
      'faq': 'නිතර අසන ප්‍රශ්න',
      'privacy_policy': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
      'contact_support': 'සහාය අමතන්න',
      'language': 'භාෂාව',
      'language_changed': 'භාෂාව {language} වෙත වෙනස් කරන ලදි',
      'account': 'ගිණුම',
      'edit_profile': 'පැතිකඩ සංස්කරණය',
      'change_password': 'මුරපදය වෙනස් කරන්න',
      'trip_history': 'ගමන් ඉතිහාසය',
      'preferences': 'වරණ',
      'notifications': 'දැනුම්දීම්',
      'receive_trip_alerts': 'ගමන් දැනුම්දීම් ලබා ගන්න',
      'sound_effects': 'ශබ්ද ප්‍රභාව',
      'play_sounds_for_actions': 'ක්‍රියා සඳහා ශබ්ද ධාවනය කරන්න',
      'vibration': 'කම්පනය',
      'vibrate_on_notifications': 'දැනුම්දීම්දී කම්පනය',
      'map_style': 'සිතියම් විලාසය',
      'distance_unit': 'දුර ඒකකය',
      'kilometers': 'කිලෝමීටර්',
      'miles': 'සැතපුම්',
      'app_information': 'යෙදුම් තොරතුරු',
      'about_app': 'යෙදුම ගැන',
      'rate_app': 'යෙදුමට ඇගයීමක් දාන්න',
      'share_feedback': 'ඔබේ ප්‍රතිචාර බෙදාගන්න',
      'get_help': 'උදව් ලබා ගන්න',
      'clear_cache': 'කෑෂ් මකන්න',
      'clear_cache_title': 'කෑෂ් මකන්න',
      'clear_cache_message':
          'මෙය තාවකාලික ගොනු සහ රූප කෑෂ් {cacheSize} ඉවත් කරයි. ඔබගේ ගිණුම් දත්තට බලපෑමක් නැත.',
      'clear': 'මකන්න',
      'logout_confirm': 'ඔබට ඉවත් වීමට අවශ්‍යද?',
      'version': 'අනුවාදය',
      'unknown': 'නොදනී',
      'map_style_changed': 'සිතියම් විලාසය {style} ලෙස වෙනස් විය',
      'cache_cleared': 'කෑෂ් සාර්ථකව මකා ඇත',
      'cache_clear_failed': 'කෑෂ් මකා දැමීමට අසමත් විය',
      'logout_failed': 'ඉවත් වීමට අසමත් විය',
      'notification_permission_denied': 'දැනුම්දීම් අවසරය ප්‍රතික්ෂේප විය',
      'welcome_back': 'නැවත සාදරයෙන් පිළිගනිමු',
      'sign_in_to_continue': 'රියදුරු ලෙස ඉදිරියට යාමට පුරන්න',
      'email_address': 'ඊමේල් ලිපිනය',
      'password': 'මුරපදය',
      'enter_password': 'ඔබගේ මුරපදය ඇතුල් කරන්න',
      'dont_have_account': 'ගිණුමක් නැද්ද? මෙහි ලියාපදිංචි වන්න',
      'already_have_account_login': 'දැනටමත් ගිණුමක් ඇතද? මෙහි පුරන්න',
      'welcome': 'සාදරයෙන් පිළිගනිමු',
      'create_account': 'නව පරිශීලක ගිණුමක් සාදන්න',
      'username': 'පරිශීලක නාමය',
      'phone_number': 'දුරකථන අංකය',
      'vehicle_number': 'වාහන අංකය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'reenter_password': 'ඔබගේ මුරපදය නැවත ඇතුල් කරන්න',
      'no_network':
          'ජාල සම්බන්ධතාවයක් නොමැත. Wi-Fi හෝ ජංගම දත්ත ක්‍රියාත්මක කරන්න.',
      'no_internet': 'ජාලයට සම්බන්ධයි, නමුත් අන්තර්ජාල ප්‍රවේශයක් නොමැත.',
      'please_write_valid_email': 'වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.',
      'password_min_6': 'ඔබගේ මුරපදය අක්ෂර 6ක් හෝ වැඩි විය යුතුය.',
      'name_min_4': 'ඔබගේ නම අක්ෂර 4ක් හෝ වැඩි විය යුතුය.',
      'phone_min_10': 'ඔබගේ දුරකථන අංකය අක්ෂර 10ක් හෝ වැඩි විය යුතුය.',
      'passwords_no_match': 'මුරපද ගැලපෙන්නේ නැත.',
      'signing_in_wait': 'පුරනය වෙමින්... කරුණාකර රැඳී සිටින්න',
      'registering_wait': 'ලියාපදිංචි වෙමින්... කරුණාකර රැඳී සිටින්න',
      'something_wrong': 'දෝෂයක් ඇතිවිය. නැවත උත්සාහ කරන්න.',
      'invalid_email_address': 'කරුණාකර වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.',
      'no_account_for_email': 'මෙම ඊමේල් ලිපිනයට ගිණුමක් හමු නොවීය.',
      'incorrect_password': 'වැරදි මුරපදය. නැවත උත්සාහ කරන්න.',
      'network_error': 'ජාල දෝෂයක්. ඔබගේ අන්තර්ජාල සම්බන්ධතාවය පරීක්ෂා කරන්න.',
      'no_user_data': 'පරිශීලක දත්ත හමු නොවීය. සහාය කණ්ඩායම අමතන්න.',
      'account_blocked': 'ඔබගේ ගිණුම අවහිර කර ඇත. සහාය කණ්ඩායම අමතන්න.',
      'email_registered': 'මෙම ඊමේල් ලිපිනය දැනටමත් ලියාපදිංචි කර ඇත.',
      'weak_password': 'මුරපදය දුර්වලයි. අක්ෂර 6කට වඩා භාවිතා කරන්න.',
      'report_ambulance_issues': 'ගිලන් රථ ගැටලු වාර්තා කරන්න',
      'report_issue_desc':
          'ඊළඟ පැවරුමට පෙර සේවා, නඩත්තු, දෝෂ හෝ වෙනත් ගැටලු වාර්තා කරන්න.',
      'report_issue': 'ගැටලුව වාර්තා කරන්න',
      'current_assignment': 'වත්මන් පැවරුම',
      'trip_id': 'ගමන් හැඳුනුම් අංකය',
      'pick_up_from': 'ගන්නා ස්ථානය',
      'destination': 'ගමනාන්තය',
      'start_navigation': 'සංචාලනය ආරම්භ කරන්න',
      'report_issue_type': 'ගැටලු වර්ගය වාර්තා කරන්න',
      'choose_issue_type': 'ඔබ වාර්තා කිරීමට අවශ්‍ය ගැටලුව තෝරන්න.',
      'service': 'සේවාව',
      'maintenance': 'නඩත්තු',
      'breakdown': 'දෝෂය',
      'other_problems': 'වෙනත් ගැටලු',
      'add_extra_details': 'අවශ්‍ය නම් වැඩි විස්තර එක් කරන්න (විකල්ප).',
      'describe_problem': 'ගැටලුව විස්තර කරන්න...',
      'submit': 'යවන්න',
      'select_navigation_method': 'සංචාලන ක්‍රමය තෝරන්න',
      'google_maps': 'Google Maps',
      'use_external_google_maps': 'බාහිර Google Maps යෙදුම භාවිතා කරන්න',
      'medigo_navigation': 'MediGo Navigation',
      'stay_inside_app': 'MediGo යෙදුම තුළම සිටින්න',
      'priority_standard': 'සාමාන්‍ය',
      'priority_critical': 'අතිශය වැදගත්',
      'priority_urgent': 'හදිසි',
      'location_permission_not_granted': 'ස්ථාන අවසරය ලබා දී නොමැත',
      'unable_get_current_location': 'වත්මන් ස්ථානය ලබා ගැනීමට නොහැකි විය',
      'issue_report_sent_with_details':
          '{issue} වාර්තාව අමතර විස්තර සමඟ යවන ලදි.',
      'issue_report_sent': '{issue} වාර්තාව සාර්ථකව යවන ලදි.',
      'could_not_open_google_maps': 'Google Maps විවෘත කළ නොහැක',
      'feedback_support': 'ප්‍රතිචාර සහ සහාය',
      'please_login_trip_history': 'ගමන් ඉතිහාසය බැලීමට කරුණාකර පුරනය වන්න',
      'loading_trip_history': 'ගමන් ඉතිහාසය පූරණය කරමින්...',
      'profile_updated_success': 'පැතිකඩ සාර්ථකව යාවත්කාලීන කරන ලදී',
      'feedback_sent_success': 'ප්‍රතිචාරය සාර්ථකව යවන ලදී',
      'feedback_send_failed': 'ප්‍රතිචාරය යැවීමට අසමත් විය',
    },
    'ta': {
      'app_title': 'MediGo ஓட்டுநர் பயன்பாடு',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'english': 'English',
      'sinhala': 'සිංහල',
      'tamil': 'தமிழ்',
      'get_started': 'தொடங்குங்கள்',
      'already_have_account': 'எனக்கு ஏற்கனவே கணக்கு உள்ளது',
      'start_tagline_title': 'வேகமான, நம்பகமான ஆம்புலன்ஸ் மேலாண்மை',
      'start_tagline_subtitle':
          'நேரடி கண்காணிப்பு, தடையற்ற ஒத்துழைப்பு மற்றும் திறமையான நோயாளி சேவை',
      'feature_tracking': 'நேரடி ஓட்டுநர் மற்றும் நோயாளர் கண்காணிப்பு',
      'feature_dispatch': 'வேகமான அனுப்பல் மற்றும் ஒருங்கிணைப்பு',
      'feature_secure': 'பாதுகாப்பான ஓட்டுநர் அணுகல்',
      'login': 'உள்நுழை',
      'signup': 'பதிவு செய்',
      'logout': 'வெளியேறு',
      'cancel': 'ரத்து செய்',
      'settings': 'அமைப்புகள்',
      'home': 'முகப்பு',
      'history': 'வரலாறு',
      'feedback_complaints': 'பின்னூட்டம் / புகார்கள்',
      'faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'contact_support': 'ஆதரவை தொடர்புகொள்',
      'language': 'மொழி',
      'language_changed': 'மொழி {language} ஆக மாற்றப்பட்டது',
      'account': 'கணக்கு',
      'edit_profile': 'சுயவிவரம் திருத்து',
      'change_password': 'கடவுச்சொல்லை மாற்று',
      'trip_history': 'பயண வரலாறு',
      'preferences': 'விருப்பங்கள்',
      'notifications': 'அறிவிப்புகள்',
      'receive_trip_alerts': 'பயண அறிவிப்புகளை பெறுக',
      'sound_effects': 'ஒலி விளைவுகள்',
      'play_sounds_for_actions': 'செயல்களுக்கு ஒலி இயக்கு',
      'vibration': 'அதிர்வு',
      'vibrate_on_notifications': 'அறிவிப்புகளில் அதிர்வு',
      'map_style': 'வரைபட பாணி',
      'distance_unit': 'தூர அலகு',
      'kilometers': 'கிலோமீட்டர்கள்',
      'miles': 'மைல்கள்',
      'app_information': 'பயன்பாட்டு தகவல்',
      'about_app': 'பயன்பாடு பற்றி',
      'rate_app': 'பயன்பாட்டை மதிப்பிடு',
      'share_feedback': 'உங்கள் பின்னூட்டத்தை பகிரவும்',
      'get_help': 'உதவி பெறுக',
      'clear_cache': 'கேஷ் நீக்கு',
      'clear_cache_title': 'கேஷ் நீக்கு',
      'clear_cache_message':
          'இது {cacheSize} தற்காலிக கோப்புகள் மற்றும் கேஷ் படங்களை நீக்கும். உங்கள் கணக்கு தரவு பாதிக்கப்படாது.',
      'clear': 'அழி',
      'logout_confirm': 'நீங்கள் உண்மையில் வெளியேற விரும்புகிறீர்களா?',
      'version': 'பதிப்பு',
      'unknown': 'தெரியாது',
      'map_style_changed': 'வரைபட பாணி {style} ஆக மாற்றப்பட்டது',
      'cache_cleared': 'கேஷ் வெற்றிகரமாக நீக்கப்பட்டது',
      'cache_clear_failed': 'கேஷ் நீக்க இயலவில்லை',
      'logout_failed': 'வெளியேற முடியவில்லை',
      'notification_permission_denied': 'அறிவிப்பு அனுமதி மறுக்கப்பட்டது',
      'welcome_back': 'மீண்டும் வரவேற்கிறோம்',
      'sign_in_to_continue': 'ஓட்டுநராக தொடர உள்நுழைக',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'password': 'கடவுச்சொல்',
      'enter_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'dont_have_account': 'கணக்கு இல்லையா? இங்கே பதிவு செய்யவும்',
      'already_have_account_login': 'ஏற்கனவே கணக்கு உள்ளதா? இங்கே உள்நுழைக',
      'welcome': 'வரவேற்பு',
      'create_account': 'புதிய பயனர் கணக்கை உருவாக்கவும்',
      'username': 'பயனர் பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'vehicle_number': 'வாகன எண்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
      'reenter_password': 'கடவுச்சொல்லை மீண்டும் உள்ளிடவும்',
      'no_network':
          'நெட்வொர்க் இணைப்பு இல்லை. Wi-Fi அல்லது மொபைல் டேட்டாவை இயக்கவும்.',
      'no_internet':
          'நெட்வொர்க்கில் இணைந்துள்ளீர்கள், ஆனால் இணைய அணுகல் இல்லை.',
      'please_write_valid_email': 'சரியான மின்னஞ்சலை உள்ளிடவும்.',
      'password_min_6': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',
      'name_min_4': 'பெயர் குறைந்தது 4 எழுத்துகள் இருக்க வேண்டும்.',
      'phone_min_10': 'தொலைபேசி எண் குறைந்தது 10 எழுத்துகள் இருக்க வேண்டும்.',
      'passwords_no_match': 'கடவுச்சொற்கள் பொருந்தவில்லை.',
      'signing_in_wait': 'உள்நுழைகிறது... தயவுசெய்து காத்திருக்கவும்',
      'registering_wait': 'பதிவு செய்கிறது... தயவுசெய்து காத்திருக்கவும்',
      'something_wrong': 'சிக்கல் ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
      'invalid_email_address': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
      'no_account_for_email': 'இந்த மின்னஞ்சலுக்கு கணக்கு இல்லை.',
      'incorrect_password': 'தவறான கடவுச்சொல். மீண்டும் முயற்சிக்கவும்.',
      'network_error': 'நெட்வொர்க் பிழை. இணைய இணைப்பை சரிபார்க்கவும்.',
      'no_user_data': 'பயனர் தரவு கிடைக்கவில்லை. ஆதரவை தொடர்புகொள்ளவும்.',
      'account_blocked':
          'உங்கள் கணக்கு முடக்கப்பட்டுள்ளது. ஆதரவை தொடர்புகொள்ளவும்.',
      'email_registered': 'இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.',
      'weak_password':
          'கடவுச்சொல் பலவீனமாக உள்ளது. குறைந்தது 6 எழுத்துகள் பயன்படுத்தவும்.',
      'report_ambulance_issues': 'ஆம்புலன்ஸ் பிரச்சினைகளை அறிவிக்கவும்',
      'report_issue_desc':
          'அடுத்த பணிக்கு முன் சேவை, பராமரிப்பு, பழுது அல்லது பிற பிரச்சினைகளை அறிவிக்கவும்.',
      'report_issue': 'பிரச்சினையை அறிவி',
      'current_assignment': 'தற்போதைய பணி',
      'trip_id': 'பயண எண்',
      'pick_up_from': 'எடுத்து செல்ல வேண்டிய இடம்',
      'destination': 'இலக்கு',
      'start_navigation': 'வழிசெலுத்தலை தொடங்கு',
      'report_issue_type': 'பிரச்சினை வகை',
      'choose_issue_type':
          'நீங்கள் அறிவிக்க விரும்பும் பிரச்சினையை தேர்ந்தெடுக்கவும்.',
      'service': 'சேவை',
      'maintenance': 'பராமரிப்பு',
      'breakdown': 'பழுது',
      'other_problems': 'மற்ற பிரச்சினைகள்',
      'add_extra_details':
          'தேவைப்பட்டால் கூடுதல் விவரங்களைச் சேர்க்கவும் (விருப்பம்).',
      'describe_problem': 'பிரச்சினையை விவரிக்கவும்...',
      'submit': 'சமர்ப்பிக்கவும்',
      'select_navigation_method': 'வழிசெலுத்தல் முறையை தேர்ந்தெடுக்கவும்',
      'google_maps': 'Google Maps',
      'use_external_google_maps':
          'வெளிப்புற Google Maps பயன்பாட்டைப் பயன்படுத்தவும்',
      'medigo_navigation': 'MediGo வழிசெலுத்தல்',
      'stay_inside_app': 'MediGo பயன்பாட்டின் உள்ளே தொடரவும்',
      'priority_standard': 'சாதாரண',
      'priority_critical': 'மிக அவசரம்',
      'priority_urgent': 'அவசரம்',
      'location_permission_not_granted': 'இருப்பிட அனுமதி வழங்கப்படவில்லை',
      'unable_get_current_location': 'தற்போதைய இருப்பிடத்தை பெற முடியவில்லை',
      'issue_report_sent_with_details':
          '{issue} அறிக்கை கூடுதல் விவரங்களுடன் அனுப்பப்பட்டது.',
      'issue_report_sent': '{issue} அறிக்கை வெற்றிகரமாக அனுப்பப்பட்டது.',
      'could_not_open_google_maps': 'Google Maps திறக்க முடியவில்லை',
      'feedback_support': 'பின்னூட்டம் மற்றும் ஆதரவு',
      'please_login_trip_history': 'பயண வரலாற்றைப் பார்க்க உள்நுழையவும்',
      'loading_trip_history': 'பயண வரலாறு ஏற்றப்படுகிறது...',
      'profile_updated_success': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'feedback_sent_success': 'பின்னூட்டம் வெற்றிகரமாக அனுப்பப்பட்டது',
      'feedback_send_failed': 'பின்னூட்டத்தை அனுப்ப முடியவில்லை',
    },
  };

  static const Map<String, String> _fallbackEnglish = {
    'app_title': 'MediGo Driver Application',
    'select_language': 'Select Language',
    'english': 'English',
    'sinhala': 'Sinhala',
    'tamil': 'Tamil',
    'get_started': 'Get Started',
    'already_have_account': 'I already have an account',
    'start_tagline_title': 'Fast, Reliable Ambulance Management',
    'start_tagline_subtitle':
        'Real-time tracking, seamless coordination, and efficient patient care delivery',
    'feature_tracking': 'Live driver & patient tracking',
    'feature_dispatch': 'Faster dispatch & coordination',
    'feature_secure': 'Secure driver access',
    'login': 'Login',
    'signup': 'Sign Up',
    'logout': 'Logout',
    'cancel': 'Cancel',
    'settings': 'Settings',
    'home': 'Home',
    'history': 'History',
    'feedback_complaints': 'Feedback / Complaints',
    'faq': 'FAQ',
    'privacy_policy': 'Privacy Policy',
    'contact_support': 'Contact Support',
    'language': 'Language',
    'language_changed': 'Language changed to {language}',
    'account': 'Account',
    'edit_profile': 'Edit Profile',
    'change_password': 'Change Password',
    'trip_history': 'Trip History',
    'preferences': 'Preferences',
    'notifications': 'Notifications',
    'receive_trip_alerts': 'Receive trip alerts',
    'sound_effects': 'Sound Effects',
    'play_sounds_for_actions': 'Play sounds for actions',
    'vibration': 'Vibration',
    'vibrate_on_notifications': 'Vibrate on notifications',
    'map_style': 'Map Style',
    'distance_unit': 'Distance Unit',
    'kilometers': 'Kilometers',
    'miles': 'Miles',
    'app_information': 'App Information',
    'about_app': 'About App',
    'rate_app': 'Rate App',
    'share_feedback': 'Share your feedback',
    'get_help': 'Get help',
    'clear_cache': 'Clear Cache',
    'clear_cache_title': 'Clear Cache',
    'clear_cache_message':
        'This will remove {cacheSize} of temporary files and cached images. Your account data will not be affected.',
    'clear': 'Clear',
    'logout_confirm': 'Are you sure you want to logout?',
    'version': 'Version',
    'unknown': 'Unknown',
    'map_style_changed': 'Map style changed to {style}',
    'cache_cleared': 'Cache cleared successfully',
    'cache_clear_failed': 'Failed to clear cache',
    'logout_failed': 'Failed to logout',
    'notification_permission_denied': 'Notification permission denied',
    'welcome_back': 'Welcome Back',
    'sign_in_to_continue': 'Sign in to continue as driver',
    'email_address': 'Email Address',
    'password': 'Password',
    'enter_password': 'Enter your password',
    'dont_have_account': "Don't have an Account? Register Here",
    'already_have_account_login': 'Already have an Account? Login Here',
    'welcome': 'Welcome',
    'create_account': 'Create a new user account',
    'username': 'Username',
    'phone_number': 'Phone Number',
    'vehicle_number': 'Vehicle Number',
    'confirm_password': 'Confirm Password',
    'reenter_password': 'Re-enter your password',
    'no_network': 'No network connection. Please turn on Wi-Fi or mobile data.',
    'no_internet': 'Connected to a network, but no internet access.',
    'please_write_valid_email': 'Please write valid email.',
    'password_min_6': 'Your password must be atleast 6 or more characters.',
    'name_min_4': 'Your name must be atleast 4 or more characters.',
    'phone_min_10': 'Your phone number must be atleast 10 or more characters.',
    'passwords_no_match': 'Passwords do not match.',
    'signing_in_wait': 'Signing in, Please wait...',
    'registering_wait': 'Registering, Please wait...',
    'something_wrong': 'Something went wrong. Please try again.',
    'invalid_email_address': 'Please enter a valid email address.',
    'no_account_for_email': 'No account found with this email.',
    'incorrect_password': 'Incorrect password. Please try again.',
    'network_error': 'Network error. Please check your internet connection.',
    'no_user_data': 'No user data found. Please contact support.',
    'account_blocked': 'Your account is blocked. Please contact support.',
    'email_registered': 'This email is already registered.',
    'weak_password': 'Password is too weak. Use at least 6 characters.',
    'report_ambulance_issues': 'Report Ambulance Issues',
    'report_issue_desc':
        'Report service, maintenance, breakdown, or other problems before your next assignment.',
    'report_issue': 'Report Issue',
    'current_assignment': 'Current Assignment',
    'trip_id': 'Trip ID',
    'pick_up_from': 'Pick Up From',
    'destination': 'Destination',
    'start_navigation': 'Start Navigation',
    'report_issue_type': 'Report Issue Type',
    'choose_issue_type': 'Choose the issue you want to report.',
    'service': 'Service',
    'maintenance': 'Maintenance',
    'breakdown': 'Breakdown',
    'other_problems': 'Other Problems',
    'add_extra_details': 'Add extra details if needed (optional).',
    'describe_problem': 'Describe the problem...',
    'submit': 'Submit',
    'select_navigation_method': 'Select Navigation Method',
    'google_maps': 'Google Maps',
    'use_external_google_maps': 'Use external Google Maps app',
    'medigo_navigation': 'MediGo Navigation',
    'stay_inside_app': 'Stay inside the MediGo app',
    'priority_standard': 'Standard',
    'priority_critical': 'Critical',
    'priority_urgent': 'Urgent',
    'location_permission_not_granted': 'Location permission not granted',
    'unable_get_current_location': 'Unable to get current location',
    'issue_report_sent_with_details': '{issue} report sent with extra details.',
    'issue_report_sent': '{issue} report sent successfully.',
    'could_not_open_google_maps': 'Could not open Google Maps',
    'feedback_support': 'Feedback & Support',
    'please_login_trip_history': 'Please log in to view trip history',
    'loading_trip_history': 'Loading trip history...',
    'profile_updated_success': 'Profile updated successfully',
    'feedback_sent_success': 'Feedback sent successfully',
    'feedback_send_failed': 'Failed to send feedback',
  };

  String t(String key, {Map<String, String> params = const {}}) {
    final value =
        _translations[languageCode]?[key] ?? _fallbackEnglish[key] ?? key;

    if (params.isEmpty) return value;

    var resolved = value;
    params.forEach((paramKey, paramValue) {
      resolved = resolved.replaceAll('{$paramKey}', paramValue);
    });
    return resolved;
  }
}

extension AppLocalizationX on BuildContext {
  AppLanguageController get _languageController => AppLanguageScope.of(this);

  String get currentLanguageCode => _languageController.languageCode;

  Future<void> setAppLanguage(String languageCode) {
    return _languageController.setLanguage(languageCode);
  }

  String t(String key, {Map<String, String> params = const {}}) {
    return AppLocalizations(currentLanguageCode).t(key, params: params);
  }
}
